### PR TITLE
Feature/batching

### PR DESCRIPTION
**Pull request by Sander80**
Hi everybody.
This is Alexander Smirnov.
After the recent talk of Gudrun I decided to plug in the QMC integrator into FIESTA.
What I found missing was the lack of the possibility for the integrator to pass batches of points into the integrator function. 
To have not just
double operator()(double* x) const
but also
void Evaluate(double * x, double * res, U count)

This is due to the fact that FIESTA is optimized to evaluate batches of points at the same time.

Well, I implemented that, and it works in FIESTA (have nto checked complex numbers yet). My first opinion is that it should be better than Vegas (anyway you know it).

But I guess you could make use of this upgrade too. So here is my pull request (hope I did not break anything).

Will be ready to answer your questions.

### CODE REVIEW

**Comment by spj101** [comment]
Thanks a lot for taking the time to document and make a pull request for the new feature. I will review it as soon as possible.

**Comment by spj101** [comment]
Hi Alexander, your changes are causing the build to fail you can see a log on travis-ci: 
https://travis-ci.org/github/mppmu/qmc/jobs/762009895

Are the checks passing on your local machine (`cd check && make`)? 
Do the above error messages make sense?

**Comment by Sander80** [comment]
Hi. I did not notice the tests, only built and checked what was needed to plug into FIESTA, and it worked.
I will try to fix them now. From the first glance mostly it is related to the complex mode.

**Comment by Sander80** [comment]
Ok there, I see one problem that needs to be solved.
I proposed the main function to have an evaluate method. But what if the user doed not need batching? Why should he care to implement it? Due to compilation reasons my change forces him to declare it. 
I am thinking what should be done. Either a preprocessor variable, or some clever c++ modern check whether this method exists

**Comment by Sander80** [comment]
```
template <typename D> struct integration_functor {
    const unsigned long long int number_of_integration_variables = 0;
    virtual HOSTDEVICE D operator()(D x[]) const;
    void evaluate(D* x, D* res, unsigned long long count) {for (unsigned long long i = 0; i != count; ++i) res[i] = this->operator()(x + i*number_of_integration_variables);}
};
```

Well, here is my suggestion, if it is ok for your usage. The integration functor should implement the basic integration functor class which I defined in the test file for the moment, but this could be moved to the core. 

For example,

```
struct zero_dim_function_t : integration_functor<double> {
    const unsigned long long int number_of_integration_variables = 0;
    HOSTDEVICE double operator()(double x[]) { return 1; }
} zero_dim_function;
```

In this case if the user does not implement the evaluate function it uses the default evaluate function with a cycle from the base class.

--------------------------------------

This fixes one of the two types of errors, I will inspect the second one too.

**Comment by spj101** [comment]
Thanks for looking into this @Sander80. 

I am a little bit worried that making the `operator()` a `virtual` function will not play well with CUDA, according to the [programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#virtual-functions) we can't use virtual functions created in host code on the device and I suspect this is what will happen now. We actually copy the functor on the device, I must admit I'm not 100% sure if this violates the rule in the programming guide.

Do the checks pass when you compile and run on a GPU locally? Unfortunately, our CI does not check the GPU side of things at all, I can do this locally once checks are passing, static code analysis is clear (`cd check && make cppcheck`) and coverage is ok.

Might be worth checking this construction is valid CUDA code before you get too far implementing it.

**Comment by Sander80** [comment]
I am still stuck with the fail of the build due to const appearing in decltype in the complex case. Then I will try to look at cuda.
However the virtual word can be safely removed if needed. It is there only for the user not to forget to implement the () operator in his functor.

**Comment by spj101** [comment]
Hi @Sander80, I now had a closer look at what you are trying to achieve here. 

I'm not entirely sure that I understand why you would want this change. The logic is that the user provides a `T func(D x[])` that will be integrated over the unit hyper-cube. The integrator itself then generates the points to be sampled either on the CPU or the GPUs (depending on the device list). The user never needs to provide a list of points to be sampled and can only influence the distribution of points to be sampled via:
* the fit function provided
* the integral transform

The actual sampling for any individual run is entirely handled internally by the package. This also means there is essentially 0 overhead to using the GPUs because a list of points to sample is never transferred to the devices, they generate their own list of points to sample.

Would it perhaps be easier to modify FIESTA to just call the integrator and not try to influence the points to be sampled? (Genuine question, I am naive about this).

**Comment by Sander80** [comment]
The idea is to add to `T func(D x[])` a second possible interface `void Evaluate(double * x, double * res, U count)`

FIESTA is not interfering the points sampled at all. But it evaluates the integrand in batches of points which leads to intenal optimizations enabled and can be up to 4 times faster.

By the way, it finally passed the tests. Only coverage for the evaluate function is missing, and Cuda should be checked

**Comment by Sander80** [comment]
It's similar to CUDA, what is called SIMD, single instruction multiple data. CPU also has these features, and the function evaluation in FIESTA is organized in a way so that it takes use of those. Requesting FIESTA to request a single point at a time leads to a serious downgrade.

**Comment by spj101** [comment]
Ok, I see. I wonder, did you check this timing with a batch size of 1 vs a larger batch using the code you implemented for the qmc? Do you indeed see this factor of 4 difference in timing? (This could be something we might look into using if so)

**Comment by Sander80** [comment]
From withing FIESTA - surely yes, that was the reason I started it.

```
CIntegratePool 4.2.dev
Threads: 4
Path: /home/sander/fiesta4/FIESTA4/./
Version: 3b0704e upgrading QMC, using the batching option
TT library version: 7f710cf Single-threaded BLAS
Terms of order 0-{0, 0}: 2419, max vars: 7
Integrating..........134.55 seconds
Average number of sampling points: 266240
```

becomes

```
Terms of order 0-{0, 0}: 2419, max vars: 7
Integrating..........43.391 seconds
Average number of sampling points: 266240
Result: 20.73771206479737 +- 0.001155864669846778
```

You also can take use of it, but yoy will have to rewrite the way the function is evaluated. It should be able to have batch evaluation loops, then the compiler will probably take care of vectorization.

So now how does one check the CUDA part? 
And I surely can increase the coverage,  but let us get sure that the whole concept is accepted. Are you ready to move the base functor class with a pure vistual operator () to the core from samples?

**Comment by Sander80** [comment]
> When a function in a derived class overrides a virtual function in a base class, the execution space specifiers (i.e., __host__, __device__) on the overridden and overriding functions must match.
> 
> It is not allowed to pass as an argument to a __global__ function an object of a class with virtual functions.
> 
> If an object is created in host code, invoking a virtual function for that object in device code has undefined behavior.
> 
> If an object is created in device code, invoking a virtual function for that object in host code has undefined behavior.
> 

And so what? We are not going to call the () operator for the base class. It is a pure virtual function that is there only for the reason to have the default Evaluate function in that class that runs the () operator in a cycle. And the cuda implementation is not going to call the Evaluate function anyway.

**Comment by Sander80** [comment]
CUDA seems to work for me.

So the main question is - are you accepting the idea witht the base class with a virtual member? 
The problem is that this will break the user code.

A collegue of mine suggested another way to derive the functors that wish to use batching from a special base class and use `if constexpr` to check this. This won't break the existing code but requires c++17.

**Comment by spj101** [comment]
Thanks a lot for checking this.

* I definitely think we want this batch feature especially since you demonstrated it is very useful in at least your case.
* I must be misinterpreting the CUDA programming guide because I understood it as meaning that any class with a virtual or overridden virtual function should not be passed to a global function, which is now precisely what is done. Maybe it helps that we never call the overridden virtual function on the device (but the guide makes no mention of not calling virtual/overridden virtual functions)

Since the usual mode of operation is now essentially a special case of the batch mode (with batch size 1), I was considering if the call operator could be overloaded with an extra defaulted argument or if `std::enable_if` could be used to decide what to pass to the call operator of the functor the user provides. Essentially, making the batch mode (with batch size 1) the default.

When we originally wrote this code we stuck very definitely to `c++11`, but a few years have passed now. Perhaps `c++17` support is widespread enough for us to bump the required `c++` version.

**Comment by Sander80** [comment]
> Since the usual mode of operation is now essentially a special case of the batch mode (with batch size 1)
It is close, but requires extra memory allocation. Just swithing to batching without rewriting the integrand evaluator will decrease performance a bit, but perhaps it's neglible.

So what should we do now? Do you wish me to add access to my fork so that you could contribute to this branch without merging it to the master? Or perhaps the destination of the pull request could be changed to another branch? 

Going to master in the current state might be too much because it leads to obligatory changes in the user code. 

std::enable_if - I am not very good at writing templates. If there is a way to stick to c++11 or 14 then perhaps it should be left as it is - the compilers at clusters might be somewhat old.

Perhaps the insertion should be done in the integrate function before it adds a fitting and a transform, since here it can check whether the base function has the Evaluate method or something.

**Comment by Sander80** [comment]
Hi. I am back to this pull request. It is in my plans to make a change so that the code will work in case the provided class has no Evaluate function, so it this case my changes can be made without affecting the code using QMC. However this will require an upgrade to c++17 to have **if constexpr**
By the way, it is in my planc to release FIESTA in autumn, and I switched to c++17

**Comment by spj101** [comment]
Hi @Sander80, apologies for the lack of support with this issue so far, it has been in the back of my mind as I finished a few other projects.

I agree with what you are proposing and I think that this new feature can be implemented in such a way that the interface is completely backwards compatible:
* A new member variable can be added to the qmc class, something like ``cpubatchsize``
* The ``operator()`` function in the user's functor can be overloaded. We currently have ``operator()(double* x) const`` but a second overload could take ``operator()(double[] x, int batchsize) const``.
* We will switch to c++17 support and then ``if constexpr`` can be used to detect the presence of the overloaded operator and use it if the present device is CPU and ``cpubatchsize!=1``.

I'm not completely sure if your previous implementation would work if a user opted to use both a CPU and a GPU device. However this ends up being implemented, clearly, we don't want the CPUs and GPUs computing the same points or the CPU blocking the GPU from computing points. The mechanism for distributing points that is implemented in the master should be able to handle this without big changes.

**Comment by Sander80** [comment]
I am currently playing with the code and trying a change in none.hpp but for the moment it is not working, something is wrong with my types

```
    ¦   template <typename T, typename DP, typename RP, typename U> static constexpr bool hasEvaluate(...) {
    ¦   ¦   return false;
    ¦   }

    ¦   template <typename T, typename DP, typename RP, typename U> static constexpr bool hasEvaluate(int, decltype((std::declval<T>().evaluate(DP(), RP(), U()))) = 0) {
    ¦   ¦   return true;
    ¦   }
```
```

    ¦   ¦   auto operator()(D* x) -> decltype(f(x))
    ¦   ¦   {
    ¦   ¦   ¦   return f(x);
    ¦   ¦   }
    ¦   ¦   void evaluate(D* x, decltype(f(x))* res, U count)
    ¦   ¦   {
    ¦   ¦   ¦   if constexpr (hasEvaluate<I, D*, decltype(f(x))*, U>(0)) {
    ¦   ¦   ¦   ¦   f.evaluate(x, res, count);
    ¦   ¦   ¦   } else {
    ¦   ¦   ¦   ¦   printf("false\n");
    ¦   ¦   ¦   }
    ¦   ¦   }

```
(inspired by this example: http://blog.abuksigun.com/2018/09/the-simplest-way-to-check-method-exists.html?m=1)

But for the moment it fails

**Comment by Sander80** [comment]
The idea of the code snippet is to check whether the passed functor has the Evaluate function (or it can be replaced with an overloaded operator()(double[] x, int batchsize) later).

**Comment by Sander80** [comment]
I think I know how to fix it. This snippet does not work for a void function

**Comment by spj101** [comment]
Glad that this works now. I was looking for ways to do this and quite liked [this](http://coliru.stacked-crooked.com/a/dff6ff04ab058c29) which is explained [here](https://www.cppstories.com/2019/07/detect-overload-from-chars/). Not sure if this code is clearer.

In this example, they are checking for specific types but I suppose checking for the number of arguments (and their types) is pretty similar.

**Comment by Sander80** [comment]
I've pushed a working code to the branch (only the none transform)
It requires the evaluate function to return int (do not know how to do it with void).
Are you sure you wish to have an overloaded operator? What is it going to return, a pointer? Who will be responsible for allocating memory in this case?

**Comment by spj101** [comment]
Thanks for this. You are right, looking at the code it is clear that the ``Evaluate`` (or equivalent) function must be passed the ``res`` pointer so it can write its results, exactly as you have done. I think it should be ok to do this but just name the function ``operator()`` or does this not work?

**Comment by Sander80** [comment]
I guess in can be an operator with 3 parameters (the coordinates, the place to write results, the count), I need to check that.
However I would also wish to somehow get rid of the return type of Evaluate which is meaningless, but do not know yet how to do it

**Comment by Sander80** [comment]
Switched to operator(). Still more the return type of th eoverloaded operator has to be int

**Comment by Sander80** [comment]
Now the check for batching was added everywhere.
The code should now not break backward compatibility, please check it.

The only missing part is the return type of the overloaded operator with 3 parameters, but it is not critical.

Would you perhaps consider pulling it to master now?

**Comment by Sander80** [comment]
```
template <typename T, typename DP, typename RP, typename U> static constexpr bool hasBatching(int, decltype(std::is_void<decltype(std::declval<T>().operator()(DP(), RP(), U()))>::value) result = false) {
    return std::is_void<decltype(std::declval<T>().operator()(DP(), RP(), U()))>::value;
}

```
finally checking for void return type

**Comment by spj101** [comment]
Thanks a lot for adding this feature. I am in principle happy to merge it once we have it well tested.

I think that the current version of this code has a bug, but I did not track it down yet. 
Running `1_minimal_demo` on the `master` we get:
```
MACTHXJONES:examples sj$ ./1_minimal_demo.out
integral = 1.249999999620490e-01
error    = 6.030624788657490e-11
MACTHXJONES:examples sj$ ./1_minimal_demo.out
integral = 1.250000000566885e-01
error    = 5.254288571081954e-11
MACTHXJONES:examples sj$ ./1_minimal_demo.out
integral = 1.250000000152124e-01
error    = 5.244774015159087e-11
MACTHXJONES:examples sj$ ./1_minimal_demo.out
integral = 1.249999999645722e-01
error    = 5.101030796132621e-11
MACTHXJONES:examples sj$ ./1_minimal_demo.out
integral = 1.250000000139247e-01
error    = 4.899103176202474e-11
```

Comparing to `11_batching_demo` on this branch (even if we set `batching=false`):
```
MACTHXJONES:examples sj$ ./11_batching_demo.out
integral = 1.249848073062131e-01
error    = 1.320803935969642e-05
MACTHXJONES:examples sj$ ./11_batching_demo.out
integral = 1.250018855716860e-01
error    = 1.651107633179496e-05
MACTHXJONES:examples sj$ ./11_batching_demo.out
integral = 1.250002398135245e-01
error    = 1.271253898970790e-05
MACTHXJONES:examples sj$ ./11_batching_demo.out
integral = 1.250092110528746e-01
error    = 1.532709255661876e-05
MACTHXJONES:examples sj$ ./11_batching_demo.out
integral = 1.249949387852980e-01
error    = 1.471507897527491e-05
```

Also, I wonder, would you mind taking a look at `11_batching_demo`? How would we implement this such that we get the large speed up you reported? This would be a great way to demonstrate this new feature.

I will continue bug hunting. Thanks again for the feature.

**Comment by spj101** [comment]
- [x] Verify `make_singleheader.py` works
- [ ] Alter `11_batching_demo` to demonstrate potential improved performance on CPU
- [x] Fix bug leading to high variance of results (and larger error)
- [x] Check that code does not break GPU support (GPUs should not compute batches)
- [x] Check that points are not recomputed if batches are enabled when using both CPUs and GPUs
- [x] Add test cases in `test_qmc_core`
- [x] Run `cppcheck` after new test cases (currently clean)

I am working through the tasks that I can.

**Comment by Sander80** [comment]
Are you sure with the tests?
I switche to your master branch and get
integral = 0.124981
error    = 1.19761e-05

**Comment by Sander80** [comment]
I see it
integrators::Qmc<double,double,MAXVAR,integrators::transforms::Korobov<3>::type> integrator;
not
None transform

**Comment by spj101** [comment]
Ah, of course! My mistake, I added the test while looking at the `None` transform. Fixed.

**Comment by Sander80** [comment]
Now about the example. 
Let me present a scheme of the code for you because you have your own prefered methods of allocation and such
So in the overloaded operator `void operator()(double* x, double* res, unsigned long long int batchsize)` you should
1) Transpose the data order. It should go in the order that points are changed first, only then coordinates
meaning if i goes from 0 to batchsize then we have
x[0, 0], x[1, 0], ... x[batchsize-1, 0], x[0, 1], x[1,1], ...x[batchsize, 1], x[0, 2], x[1,2], ...x[batchsize, 2]
2) make a temporary array to store the result of x[0] * x[1] of size batchsize
3) fill it in a loop from 0 to batchsize-1, but better unrolling the loop into portions of 4 numbers
4) do the same for the final calculation

**Comment by Sander80** [comment]
The problem is that is you make those allocations each batch it might be too lengthy.
In FIESTA we prepare the structures before running the integrator

**Comment by Sander80** [comment]
Hi. I am not that far from preparing a release of FIESTA and am wondering whether you are planning to merge this pull request in near future - the reason I ask is whether I will be switching FIESTA from pulling QMC from my fork to your repository

**Comment by spj101** [comment]
Hi @Sander80 yes I will merge this into the master this week.

Thank you for your explanation of how to structure the code to benefit from this feature. I took a look at modifying `11_batching_demo` to demonstrate this but did not get very far with this just yet. This evening I will check this on GPU. After this I am happy to merge.

**Comment by Sander80** [comment]
Thank you, I'll be waiting.
By the way, after the release of FIESTA there is one subject to discuss. What would your group think aboput making a common work and paper with SecDec using the FIESTA internals for integration. I beleive we are quite good in parsing expressions and evaluating  them fast instead of compiling like it is in SecDec, but I am not that confident on the expression preparation part, and SecDec surely has some nice things there. If the FIESTA integration engine could be plugged into the SecDec scheme this could be a nice joined paper, what do you think? If your group is interested, let us discuss this after the release.

**Comment by Sander80** [comment]
Hmm I think I had a reason to remove the const word... let me check it with FIESTA

**Comment by Sander80** [comment]
Anyway the reason is gone now )

**Comment by spj101** [comment]
Thanks! I assumed it was perhaps necessary when the virtual functions were introduced but since everything is done in the compiler now I hoped it would be ok.

**Comment by spj101** [comment]
> By the way, after the release of FIESTA there is one subject to discuss. What would your group think aboput making a common work and paper with SecDec using the FIESTA internals for integration. I beleive we are quite good in parsing expressions and evaluating them fast instead of compiling like it is in SecDec, but I am not that confident on the expression preparation part, and SecDec surely has some nice things there. If the FIESTA integration engine could be plugged into the SecDec scheme this could be a nice joined paper, what do you think? If your group is interested, let us discuss this after the release.

I think this could be interesting. I have forwarded this to the whole pySecDec group, let's see if it can work.

**Comment by spj101** [comment]
I am almost ready to merge this, but I am still struggling to get any performance enhancement from batching in `11_batching_demo` so I assume I am still doing something wrong in this example. I would ideally like a simple example to demonstrate the new feature.

I understand that the `x` input array is already generated correctly and so the `operator()(double* x, double* res, unsigned long long int batchsize)` function does not need to do any transpose, the result array is already allocated. Therefore, this function should just loop over the points and call `operator()(double* x)`, have I got this wrong?

I tried with clang
```
c++ -march=native -O3 -std=c++17 -pthread -I../src 11_batching_demo.cpp -o 11_batching_demo.out -lgsl -lgslcblas -Rpass=loop-vectorize
```

It tells me
```
11_batching_demo.cpp:27:9: remark: vectorized loop (vectorization width: 4, interleaved count: 4) [-Rpass=loop-vectorize]
        for (unsigned long long int i = 0; i != batchsize; ++i) {
```
so the loop is vectorized.

However, this seems to make no difference to the timings. I tried increasing the lattice size `minn`, increasing the `maxnperpackage`. Is there a simple change that needs to be made somewhere in this example or is the structure just totally wrong to take advantage of SIMD? Perhaps also the integrand function is too simple?

Sorry that I didn't manage to figure this out yet.

**Comment by Sander80** [comment]
```
        for (unsigned long long int i = 0; i != batchsize; ++i) {
            res[i] = operator()(x + i * number_of_integration_variables);
        }
```
with return x[0]*x[1]*x[2];
This is what I see in the example now. 
so here res[0] = x[0]*x[1]*x[2], res[1] = x[3]*x[4]*x[5] and so on
This think won't get a speed improvement from SSE or AVX
For those you need to have
res[0] = x[0]*x[num]*x[2 *num], res[1] = x[1]*x[num+1]*x[2 *num+1]
In this case the compiler might take care of this in case you are lucky and evaluate res[0] and res[1] at the same time because it does not do to multiplications but an AVX multiplication of two pairs of doubles and so on.

On the other side, this example is rather simple. The sampling point generation time might be dominating the evaluation

**Comment by Sander80** [comment]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_mul_pd&expand=4891

**Comment by spj101** [comment]
@Sander80, thank you for this. I suspect that indeed the sampling point generation time is dominating the evaluation. I will make the example function a bit more complicated.

I just pushed a failing check. It seems that when `batching = true` the code sometimes tries to evaluate more points than it should and ends up calling the function with `x[...] = 0`. In the check I pushed, the function returns `nan` when `x[...] = 0` and so this spoils the result when using batching. I did not debug where the error is coming from just yet.

**Comment by Sander80** [comment]
```
    ¦   ¦   ¦   ¦   ¦   batch_count = (n / total_work_packages) + ((n % total_work_packages) ? 1 : 0);
    ¦   ¦   ¦   ¦   else
    ¦   ¦   ¦   ¦   ¦   batch_count = 1;
```
`func(x.data(), points, batch_count);`

Could be this - if n is not divisible by total_work_packages...  (perhaps I did not understand well the structure)

**Comment by Sander80** [comment]
should be
` batch_count = (n / total_work_packages) + ((i < (n % total_work_packages)) ? 1 : 0);`
I guess

**Comment by Sander80** [comment]
Fixed the test for me.
I thin the reason I did not encounter it with FIESTA is that I always used 1 core in QMC

**Comment by spj101** [comment]
> `batch_count = (n / total_work_packages) + ((i < (n % total_work_packages)) ? 1 : 0);`

I think this is now correct, thanks!

I also pushed a commit that reduces the number of memory allocations in the `compute` function, a commit that checks edge cases for batching, and I tried to improve the `11_batching_demo`.

The `11_batching_demo` still shows no speedup on my machine, compiling:
```
c++ -march=native -O3 -std=c++17 -pthread -I../src 11_batching_demo.cpp -o 11_batching_demo.out -lgsl -lgslcblas -Rpass=loop-vectorize -fno-math-errno
...
11_batching_demo.cpp:31:9: remark: vectorized loop (vectorization width: 4, interleaved count: 1) [-Rpass=loop-vectorize]
        for (unsigned long long int i = 0; i != batchsize; ++i) {
...
```
I see that indeed it is vectorized.

Running:
```
./11_batching_demo.out
Integrating without batching
  integral = 31.01515151514719
  error    = 1.313564316992873e-13
  time (s) = 11.437018758
Integrating with batching
  integral = 31.0151515151471
  error    = 1.462068481625568e-13
  time (s) = 11.003131171
```
There doesn't seem to be much effect.

Replacing the function that it evaluates with a trivial one `f(x)=1`, I see that the overhead from generating lattice points, random shifts, allocating memory etc is < 2 seconds in total. It, therefore, spends at least 8 seconds actually evaluating the function. These timings are completely different if I use `-ffast-math`, there the function becomes so fast that probably we again measure overhead. It would be really nice to have a simple example that shows some benefit of the batching as I am sure it can help!

In any case, I don't think this request will break anything now and I will merge this with the master tonight.

Thanks a lot!

**Comment by Sander80** [comment]
Now I get errors compiling with FIESTA, did not investigate yet

```
In file included from ../sources/../extra/qmc/src/qmc.hpp:31,
                 from ../sources/integrators.h:24,
                 from ../sources/integrators.cpp:8:
../sources/../extra/qmc/src/transforms/sidi.hpp: In function ‘void integrators::core::generic::compute(integrators::U, const std::vector<long long unsigned int>&, const std::vector<D>&, T*, integrators::U, integrators::U, integrators::U, integrators::U, bool, I&) [with T = double; D = double; I = integrators::transforms::SidiImpl<integrators::fitfunctions::NoneTransform<quasiMonteCarlo(IntegrationResult*)::MyFunctor, double, 32>, double, 3, void>]’:
../sources/../extra/qmc/src/transforms/sidi.hpp:81:32: error: ‘points’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   81 |                         res[i] = wgts[i] * res[i];
      |                         ~~~~~~~^~~~~~~~~~~~~~~~
In file included from ../sources/../extra/qmc/src/qmc.hpp:112,
                 from ../sources/integrators.h:24,
                 from ../sources/integrators.cpp:8:
../sources/../extra/qmc/src/core/generic/compute.hpp:20:20: note: ‘points’ was declared here
   20 |                 T* points;
      |                    ^~~~~~
../sources/../extra/qmc/src/core/generic/compute.hpp: In function ‘void integrators::core::generic::compute(integrators::U, const std::vector<long long unsigned int>&, const std::vector<D>&, T*, integrators::U, integrators::U, integrators::U, integrators::U, bool, I&) [with T = double; D = double; I = integrators::transforms::NoneImpl<integrators::fitfunctions::NoneTransform<quasiMonteCarlo(IntegrationResult*)::MyFunctor, double, 32>, double>]’:
../sources/../extra/qmc/src/core/generic/compute.hpp:56:69: error: ‘points’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   56 |                             r_element[k*r_size_over_m] += wgt*points[i];
      |                                                               ~~~~~~^
../sources/../extra/qmc/src/core/generic/compute.hpp: In function ‘void integrators::core::generic::compute(integrators::U, const std::vector<long long unsigned int>&, const std::vector<D>&, T*, integrators::U, integrators::U, integrators::U, integrators::U, bool, I&) [with T = double; D = double; I = integrators::transforms::BakerImpl<integrators::fitfunctions::NoneTransform<quasiMonteCarlo(IntegrationResult*)::MyFunctor, double, 32>, double>]’:
../sources/../extra/qmc/src/core/generic/compute.hpp:56:69: error: ‘points’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   56 |                             r_element[k*r_size_over_m] += wgt*points[i];
      |                                                               ~~~~~~^
In file included from ../sources/../extra/qmc/src/qmc.hpp:30,
                 from ../sources/integrators.h:24,
                 from ../sources/integrators.cpp:8:
../sources/../extra/qmc/src/transforms/korobov.hpp: In function ‘void integrators::core::generic::compute(integrators::U, const std::vector<long long unsigned int>&, const std::vector<D>&, T*, integrators::U, integrators::U, integrators::U, integrators::U, bool, I&) [with T = double; D = double; I = integrators::transforms::KorobovImpl<integrators::fitfunctions::NoneTransform<quasiMonteCarlo(IntegrationResult*)::MyFunctor, double, 32>, double, 3, 3>]’:
../sources/../extra/qmc/src/transforms/korobov.hpp:63:32: error: ‘points’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   63 |                         res[i] = wgts[i] * res[i];
      |                         ~~~~~~~^~~~~~~~~~~~~~~~
In file included from ../sources/../extra/qmc/src/qmc.hpp:112,
                 from ../sources/integrators.h:24,
                 from ../sources/integrators.cpp:8:
../sources/../extra/qmc/src/core/generic/compute.hpp:20:20: note: ‘points’ was declared here
   20 |                 T* points;
      |                    ^~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:14: integrators.o] Ошибка 1
make[1]: выход из каталога «/home/sander/fiesta/FIESTA4/real»
make: *** [Makefile:29: default] Ошибка 2

```

**Comment by Sander80** [comment]
A small commit seems to fix this

**Comment by spj101** [comment]
Thanks a lot for this! I will include this in the next release. Do you redistribute this with your code? In this case I should be sure to make a versioned release as soon as possible.

**Comment by Sander80** [comment]
I set it up that qmc is a git sumbodule in FIESTA, so if the user configures it with qmc usage, it is downloaded before build. Currenly it is downloaded from the fork, I will switch it to your repository now. I set it up pointing to a fixed commit, so it works any way, but pointing to a numbered release seems better.

**Comment by Sander80** [comment]
Hi, Stephen.
Are you still plannng a numbered release in the near future? Just trying to set up my tasks remaining before the publication of FIESTA

**Pull request merged**
